---
- name: Ensure .ssh directory exists.
  file:
    state: directory
    path: /root/.ssh
  when:
    - docker_swarm_enabled | bool
    - docker_swarm_initial_manager is defined
    - docker_swarm_initial_manager != inventory_hostname
  become: true

- name: Deploy Private Docker Auth SSH key.
  copy:
    dest: /root/.ssh/id_rsa
    content: "{{ docker_swarm_initial_manager_ssh_private_key }}"
    mode: 0600
  become: true

- name: Get Swarm Manager Join Tokens.
  command: "ssh {{ docker_swarm_initial_manager_ssh_username }}@{{ docker_swarm_initial_manager }} -o StrictHostKeyChecking=no -C 'docker swarm join-token --quiet {{ docker_swarm_node_type }}'"
  register: swarm_info
  when:
    - docker_swarm_enabled | bool
    - docker_swarm_initial_manager is defined
    - docker_swarm_initial_manager != inventory_hostname
  become: true

- name: Join the Swarm.
  docker_swarm:
    state: join
    advertise_addr: "{{ docker_advertise_addr }}"
    join_token: "{{ swarm_info.stdout }}"
    remote_addrs:
      - "{{ docker_swarm_initial_manager }}:2377"
  when:
    - docker_swarm_enabled | bool
    - docker_swarm_initial_manager is defined
    - docker_swarm_initial_manager != inventory_hostname
