---
- name: Get Docker's official GPG key
  apt_key:
    url: "{{ docker_repository_key_url }}"
    id: "{{ docker_repository_key_id }}"
  become: true

- name: Add Docker CE Stable Repository
  apt_repository:
    repo: "{{ docker_repository }}"
    state: present
  become: true

- name: Install docker engine
  package:
    name: "{{ docker_engine_product }}={{ docker_engine_version }}"
    state: present
  become: true

- name: Install docker cli
  package:
    name: "{{ docker_cli_product }}={{ docker_cli_version }}"
    state: present

- name: Install containerd.io
  package:
    name: containerd.io
    state: present

- name: Ensure docker group is present
  group:
    gid: '1337'
    name: docker
    state: present
    system: true
  notify: restart docker
  become: true

- name: Add user to docker group.
  user:
    name: "{{ item }}"
    groups: 
      - docker
    append: true
  loop: "{{ docker_users }}"
  become: true
