---
# handlers file for docker
- name: restart docker
  service:
    name: docker
    state: restarted
  become: true

- name: restart containx netshare
  service:
    name: docker-volume-netshare
    state: restarted
